spring:
  h2:
    console:
      enabled: true
  datasource:
    #    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    #    driver-class-name: org.h2.Driver
    #    username: sa
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/./data/testdb
      username: sa
      password:


  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

# mapper.xml 위치 지정
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: me.thewing.boardproject.domain