spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
# mapper.xml 위치 지정
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: me.thewing.boardproject.domain