GET http://localhost:8080/api/board/getlist
Accept: application/json

###

POST http://localhost:8080/api/board/insertBoard
Content-Type: application/json

{
  "title": "TITLE6",
  "content": "CONTENT6",
  "writer": "WRITER6",
  "password": 6,
  "regdate": "2020-12-06",
  "cnt": 6
}

###
GET http://localhost:8080/api/board/getBoard/1
Accept: application/json

###
GET https://dapi.kakao.com/v2/local/geo/coord2address.json?input_coord=WGS84&y=37.599191&x=126.716316
Authorization: KakaoAK 109569371036c4d6f2f7a904ae262661
Accept: application/json
###

